### ISSUE TITLE
Foundry V12

### ISSUE THREAD

**Issue by Zonenpenner** [vt-tom/dsa5-vttoms-cave-of-eternal-knowledge#5]
Leider läuft das Modul mit den ganzen wertvollen Videos nicht in Foundry v12.
Daher hoffen wir auf eine Adaption für Foundry v12! Foundry 12! Foundry 12!

Beste Grüße und danke für die tolle Arbeit!

**Comment by vt-tom** [comment]
Released a v12 Update with new Videos.
